### ISSUE TITLE
Labels for 7T parcellations

### ISSUE THREAD

**Issue by FeHoff** [yetianmed/subcortex#1]
Impressive work and it's awesome that you make everything available here !!  
I am wondering if you could also make label files for the 7T parcellations I-IV scales available?

**Comment by yetianmed** [comment]
Hi Felix,

Thanks for getting in touch.

I did not make label files for the 7T parcellation. Too much work back
then.

But you are right, I should perhaps work on it when I get the chance. Do
you need that urgently?

Ye

**Comment by FeHoff** [comment]
Hi Ye,

Thanks for the instant response. I am looking at the latest release of the UKBiobank structural data right now, and am quite curious if your fine grained 7T parcellation scale IV with 62 ROIs yields meaningful results in comparison to the 3T 54 ROIs. T1w data is not the richest of measurements.

Felix

**Comment by yetianmed** [comment]
Hi Felix,

I will work on the 7T label files soon and will keep you posted. 

Cheers,
Ye

**Comment by gjheij** [comment]
Hi all,

I would also be greatly interested in 7T-labels!

Best,
Jurjen

**Comment by SMalekiBalajoo** [comment]
Hi all,
We also are interested in 7T-labels. Is there any update?

Best,
Somayeh

**Comment by winsonfzyang** [comment]
Hi all! 
I'm also interested in the 7T-labels as we're using 7T for our imaging. Wondering as well if anyone knows of any updates on this?

Kind regards,
Winson

**Comment by yetianmed** [comment]
I have now uploaded the label file for the 7T atlas (7T-label.xlsx). Most labels are consistent with the 3T atlas.

**Comment by winsonfzyang** [comment]
Thank you so much!!
