### ISSUE TITLE
cortex-subcortex atlases in NIFTI?

### ISSUE THREAD

**Issue by eniluap** [yetianmed/subcortex#2]
Hi,
Thanks for sharing your atlases! 
Would it be possible to get the cortex-subcortex atlases in NIFTI format as well?

**Comment by yetianmed** [comment]
Hi,
Sorry for the late reply! It is not possible to store surface data in a NIFTI format but there are some other cortex atlaes that were delineated in a volumetric space (NIFTI). It would be very easy to use them together with the subcortex atlas (NIFTI) in the subcortex-only folder. Happy to help.
Cheers,
Ye
