### ISSUE TITLE
Cortex-Subcortex atlas

### ISSUE THREAD

**Issue by shilpitju** [yetianmed/subcortex#4]
Hi,

Thank you for a wonderful subcortical atlas. I am looking for the combined version of the atlas with Glasser cortical atlas. The github page only has Gordon or Schaefer ones.

Thanks,

Shilpi Modi

**Comment by yetianmed** [comment]
Hi Shilpi,

The combined version with Glasser atlas is named as:

Q1-Q6_RelatedValidation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR_Tian_Subcortex_S*.dlabel.nii

Ye

**Comment by shilpitju** [comment]
Thanks so much.
