### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oesteban** [yetianmed/subcortex#6]
Thanks for creating this wonderful resource. Unfortunately, an explicit, clear usage license is missing, which completely rules out the reutilization of the atlas by third parties.

It is possible that I missed where the license is stated, but I think it would be best for everyone to clearly state a license at the root of the repository, and that license were distributed too within the tarball referenced in the README.

Thanks very much.

**Comment by yetianmed** [comment]
Hi there,

Thanks for getting in touch. Just uploaded the license file (license.txt). 

Cheers
Ye

**Comment by oesteban** [comment]
Thanks a lot!
