### ISSUE TITLE
Mismatch between parcellation nii and labels?

### ISSUE THREAD

**Issue by bwinsto2** [yetianmed/subcortex#7]
Hello - thank you for making this great tool. I am attempting to use the Schaefer 400 S3 2mm combined atlas, but there seems to be a mismatch between the parcellation and the labels. Take, for example, SomMotB_Aud_2, which is in the Schaefer2018_400Parcels_17Networks_order_Tian_Subcortex_S3_label.txt file as Parcel #95. However, when I go to this parcel in FSLeyes, the SomMotB_Aud_2 parcel is actually under #83 (cross-referencing it with the regular Schaefer 400 parcellation). 

<img width="1106" alt="Screen Shot 2023-12-05 at 2 38 39 PM" src="https://github.com/yetianmed/subcortex/assets/61159065/88b39005-4cfc-4ce5-8afa-fb79028d6188">

<img width="1112" alt="Screen Shot 2023-12-05 at 2 39 41 PM" src="https://github.com/yetianmed/subcortex/assets/61159065/6d15d201-331d-4b30-986e-fc5b391e92ab">

<img width="1112" alt="Screen Shot 2023-12-05 at 2 39 13 PM" src="https://github.com/yetianmed/subcortex/assets/61159065/c438baf4-51a3-4c3a-924b-914d7df2941a">

I noticed that the only .nii parcellation file is in 7Network: Schaefer2018_400Parcels_7Networks_order_Tian_Subcortex_S3_MNI152NLin6Asym_2mm.nii.gz. Does this have anything to do with the problem? Am I misunderstanding something? 

Thank you for any help.

**Comment by yetianmed** [comment]
Hi there, the nii image you look at in fsleyes is the 7 network nii but the lable file you indicate is 17 network. That's why it's different. You will find the consistency if you open the 7 network lable.txt file. 

The nii parcellation is the same for 7 or 17 networks. The only difference is the label file. That's why I did not upload simply to save space. 

Hope this addresses your questions.

**Comment by bwinsto2** [comment]
Hi Dr. Tian, thanks for your response. I understand that the 7 network label file corresponds with the 7 network nii. However, as you mentioned, the 17 network label file is different than the 7 network label file. not just in naming but also in order:
![Screen Shot 2023-12-08 at 1 24 32 PM](https://github.com/yetianmed/subcortex/assets/61159065/6a8979b5-ecbc-49e8-9b4f-74839b777861)

If the nifti parcellation is the same for 7 and 17 networks, then the 17 network label file should work with the 7 network nii, but that is not the case as my first post demonstrated. 

Please let me know if I am missing something. I would like to use the 17 network label file, but as you can see, it does not work with the 7 network nii. 

thanks, 
Brian

**Comment by bwinsto2** [comment]
Update: I realized this is actually an error in the Schaefer parcellation labels!!
